django_toolkit_venv/src/django_toolkit/urls.py
# import a module and a function to manage URLs for the admin site
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include

# this variable includes the sets of URLs from the apps in the project
urlpatterns = [
    path('admin/', admin.site.urls), # this defines URLs for the admin site
    
    # for this to work, I also need to add urls.py to the learning_logs app
    path('', include('learning_logs.urls')), # this sets the base url to the homepage of learning_logs
]

django_toolkit_venv/src/learning_logs/urls.py
# Define URLs for learnning_logs
from django.urls import path # import path function -> it is needed when mapping URLs to views
from . import views # import the views module (dot tells python it is in the same directory as urls.py)

app_name = 'learning_logs' # this variable helps Django distinguish this urls.py from other urls.py files

# urlpatterns is a list of individual pages that can be requested from the learning_logs app
urlpatterns = [
    # Home page
    path('', views.index, name = 'index'), # URL pattern is a call to path function
    # empty string "" matches the base URL
    # views.index specifies to call index function in views.py
    # name = 'index' specifies a name for a URL pattern so that I can refer to it in other sections of the code
    # index is the agreed upon name for the home page
    
    # Page with all the topics
    path('topics/', views.topics, name = 'topics'),

    # Detail page for a single topic
    # The <int:topic_id> tells Django to look for URLs that have /topic after base url and then
    # It matches an integer betwee // and stores it in an argument called topic_id
    # Example: /topics/1/
    path('topics/<int:topic_id>/', views.topic, name = 'topic'),
]

django_toolkit_venv/src/learning_logs/models.py
from django.db import models # models module is already imported 0

# For the learning logs there will be a few models (classes)

# The first class is the topic (the notes will have different topics so this is to put them in proper places)

class Topic(models.Model): # inherit from the Model class (included in Django, provides basic model functionality)
    # A topic of the notes
    
    # attributes:
    text = models.CharField(max_length = 200) # title of a topic -> text is a CharField = a piece of data made up of characters to store short strings
    date_added = models.DateTimeField(auto_now_add = True) # date_added is a DateTimeField = a piece of data recording a date and time.\
    # The argument inside tells Django to automatically set this attribute to the current date and time when a new topic is created
    # For more kinds of fields that can be used in a model see: https://docs.djangoproject.com/en/4.0/ref/models/fields/

    def __str__(self):
        return self.text

# Each topic will have several entries
class Entry(models.Model): # As before Entry inherits from Model class

    topic = models.ForeignKey(Topic, on_delete = models.CASCADE) # topic attribute is a ForeignKey instance
    # which means it is a reference to another record in the database (in this case to topic)
    # It is used to create a relationship within the data (each entry is related to one topic)
    # This works because each topic has an ID associated to it (a key), so an entry can be linked to that ID
    # on_delete = models.CASCADE makes it so that when a Topic is deleted all Entries associated with it will also be deleted

    text = models.TextField() # Text field to put the notes in
    date_added = models.TimeField(auto_now_add = True) # stores when Entry was added

    # class Meta holds extra information for managing a model
    # here it sets the plural name to entries (not Entrys)
    class Meta:
        verbose_name_plural = 'entries'
    
    # return a string representation of an entry
    def __str__(self):
        str_len = len(self.text)
        if(str_len <= 50):
            return self.text
        else:
            str_to_return = self.text[:50] + '...'# return only first 50 characters
            return str_to_return

django_toolkit_venv/src/learning_logs/views.py
from django.shortcuts import render # import render function to render resopnses based on data from views
from .models import Topic # import topic model from the models file
# Create your views here.

def index(request):
    """Learning Log Home Page"""
    # render function has two arguments - request from a url and a template 
    # it uses to build the page
    return render(request, 'learning_logs/index.html')

def topics(request):
    """Learning Log Topics Page"""
    # The topics page needs to retrieve data from the database
    # I ask the database for Topic objects sorted by the date added
    topics = Topic.objects.order_by('date_added')

    # Then I define a dictionary with the name context with key topics and value as the set of topics
    context = {'topics':topics}

    # Then render function is returned to build the page, this time called with context
    # Passing context is necessary when building a page that uses data
    return render(request, 'learning_logs/topics.html', context)

def topic(request, topic_id):
    """Individual topic page."""
    # First get the topic by its id
    # This is the same command as in Django shell
    topic = Topic.objects.get(id = topic_id)

    # Then get entries associated with the topic and order according to date added
    # - tells the order to be reversed (most recent first)
    entries = topic.entry_set.order_by('-date_added')

    # Finally store everything in context dictionary
    context = {'topic':topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

django_toolkit_venv/src/learning_logs/templates/learning_logs/base.html
<!-- 
    Parent template that all pages in this project will inherit from
    First create a paragraph with the name of the project and a home page link
    To generate a link a temple tag is used - indicated by the bracket and % signs 
    The template tag below generates a URL matching a the URL pattern defined in learning_logs/urls.py 
    with name index.
    Link template is <a href = "link_url">link text</a>
    By having a template tag generate URL the links only need to be changed in the urls.py files to update them
    The first part of learning_logs:index is the namespace, and comes from the value app_name in learning_logs/urls.py
-->

<p>
    <a href = "{% url 'learning_logs:index' %}"> Learning Log</a> - 
    <a href = "{% url 'learning_logs:topics' %}"> Topics</a>
</p>


<!-- 
    This is a pair of block tags, and is a placeholder. The child template will determine the
    content that goes into this block.
-->
{% block content %}{% endblock content%}

django_toolkit_venv/src/learning_logs/templates/learning_logs/index.html
<!-- 
    Quick recap for html
    <p></p> is a paragraph
    <ul></ul> is an unordered list = bullet list
-->

<!-- As this page inherits from the parent page I first have extends tag to tell which template to inherit from-->
{% extends "learning_logs/base.html" %}

<!-- Then the child page determines what to put in the content block from the parent page-->
{% block content %}
    <p>Learning Log allows the user to save all the notes while learning</p>
{% endblock content%}

django_toolkit_venv/src/learning_logs/templates/learning_logs/topic.html
<!-- Template for individual topic page-->

{% extends 'learning_logs/base.html' %}

{% block content %}
    <!-- First print the topic name and the entries-->
    <p> Topic: {{topic}}</p>
    <p> Entries:</p>
    <ul>
        <!-- 
            For every entry  show the time it was added and its text
            The | represents a filter 0 ex. linebreaks ensures the long text includes line breaks
            rather than putting everythin in 1 line
            The rest is the same as in topics.html    
        -->
        {% for entry in entries %}
            <li>
                <p>{{ entry.date_added|date:"G:i"}}</p>
                <p>{{ entry.text|linebreaks}}</p>
            </li>
            {% empty %}
                <li>There are no entries in this topic.</li>

        {% endfor %}
    </ul>
{% endblock content %}

django_toolkit_venv/src/learning_logs/templates/learning_logs/topics.html
<!-- Template for the topics page-->

<!--
    As before the site inherits from the parent page, then puts a bullet list with all the topics
    To do that it uses a for loop that has a template like this:
        { % for item in list % } # without the spaces before and after %
            do something

        { % endfor % }
        Then it prints a variable (which needs to be wrapped in double braces)
        <li></li> indicates a list item
        the empty tag tells Django what to do if the list is empty
        

-->
{% extends "learning_logs/base.html" %}

{% block content %}
    <p>Topics</p>

    <ul>
    {% for topic in topics %}
        <li>
            <!-- 
                To each topic name add a url linking it to the corresponding topic page
                Since the url pattern requires topic_id argument I add the topic.id to the URL tag
            -->
            <a href = "{% url 'learning_logs:topic' topic.id %}">{{topic}}</a>
        </li>
        {% empty %}
            <li>No topics have been added yet.</li>
    {% endfor %}

    </ul>

{% endblock content %}